using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PollBall
{
    public class Startup
    {
      
        public void Configure(IApplicationBuilder app)
        {
            
            app.Use(async (context, next) =>
             {
                 if (context.Request.Query.ContainsKey("favorite"))
                 {
                     string selectedValue = context.Request.Query["favorite"];
                     await context.Response.WriteAsync("Selected value is: " + selectedValue);
                 }
                 else
                 {
                     await next.Invoke();
                 }
             });

            app.UseStaticFiles();

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("This text was generated by the app.Run middleware.");
            });
        }
    }
}
